# Generated by Django 6.0.3 on 2026-04-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_report_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='note',
        ),
    ]
