# Generated by Django 6.0.3 on 2026-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
