# Generated by Django 6.0.3 on 2026-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_report_note_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
