# Generated by Django 6.0.3 on 2026-04-29 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Jalan Rusak', 'Jalan Rusak'), ('Sampah', 'Sampah'), ('Lampu Mati', 'Lampu Mati'), ('Drainase', 'Drainase'), ('Keamanan', 'Keamanan')], default='Jalan Rusak', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
